AWSTemplateFormatVersion: 2010-09-09
Description: 'Cloud9 IDE environment and Elastic Container Registry repository for Falcon CI Lab'
Parameters:
  RepositoryName:
    Type: String
    Description: 'cs-jenkins-demo'
Resources:
  MyRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Ref RepositoryName