---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Ubuntu Ec2 Instance with Docker and Jenkins installed'
Parameters:
  InstanceName:
    Type: String
    Description: 'Name of the EC2 Instance'
    Default: 'fal.con-dockerJenkins'
  KeyName:
    Type: String
    Description: 'Name of the SSH Key Pair'
    Default: 'cs-key'
  RemoteIp:
    Type: String
    Description: 'IP Address to Allow-List for SSH and 8080 (Jenkins)'
    Default: 0.0.0.0/32
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
Resources: