---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Entry CFT to invoke nested stacks for Falcon CI Lab'
Parameters:
  RemoteIp:
    Type: String
    Description: 'IP Address to Allow-List for remote SSH and 8080 (Jenkins)'
    Default: 1.1.1.1/32
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
  PermissionsBoundary:
    Type: String
    Default: 'BoundaryForAdministratorAccess'
  S3Bucket:
    Type: String
  RepositoryUrl:
    Type: String
    Description: 'CodeCommit Repository URL'
  RepositoryName:
    Type: String
    Description: 'CodeCommit Repository Name'
Conditions:
  PermissionsBoundary: !Not [!Equals [!Ref PermissionsBoundary, '']]
Resources:
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${S3Bucket}.s3.amazonaws.com/iam.yaml'
      Parameters:
        PermissionsBoundary: !Ref PermissionsBoundary
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${S3Bucket}.s3.amazonaws.com/vpc.yaml'
      Parameters:
        PermissionsBoundary: !Ref PermissionsBoundary
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMStack
    Properties:
      TemplateURL: !Sub 'https://${S3Bucket}.s3.amazonaws.com/ec2.yaml'
      Parameters:
        RemoteIp: !Ref RemoteIp
        InstanceProfile: !GetAtt IAMStack.Outputs.InstanceProfileName
        PublicSubnet1: !GetAtt VPCStack.Outputs.Subnet1
        PublicSubnet2: !GetAtt VPCStack.Outputs.SubnetPublic2
        PrivateSubnet1: !GetAtt VPCStack.Outputs.SubnetPrivate1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.SubnetPrivate2
  CICDStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMStack
    Properties:
      TemplateURL: !Sub 'https://${S3Bucket}.s3.amazonaws.com/cicd.yaml'
      Parameters:
        RepositoryUrl: !Ref RepositoryUrl
        RepositoryName: !Ref RepositoryName