---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Ubuntu Ec2 Instance with Docker and Jenkins installed'
Parameters:
  RemoteIp:
    Type: String
    Description: 'IP Address to Allow-List for remote SSH and 8080 (Jenkins)'
    Default: 1.1.1.1/32
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
  PermissionsBoundary:
    Type: String
    Default: 'BoundaryForAdministratorAccess'
  S3Bucket:
    Type: String
Conditions:
  PermissionsBoundary: !Not [!Equals [!Ref PermissionsBoundary, '']]
Resources:
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${S3Bucket}.s3.amazonaws.com/iam.yaml'
      Parameters:
        S3Bucket: !Ref S3Bucket
        PermissionsBoundary: !Ref PermissionsBoundary
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${S3Bucket}.s3.amazonaws.com/ec2.yaml'
      Parameters:
        RemoteIp: !Ref RemoteIp