---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Entry CFT to invoke nested stacks for Falcon CI Lab'
Parameters:
  S3Bucket:
    Type: String
  RepositoryUrl:
    Type: String
    Description: 'CodeCommit Repository URL'
    Default: "https://git-codecommit.us-west-2.amazonaws.com/v1/repos/cs-jenkins-demo"
  RepositoryName:
    Type: String
    Description: 'CodeCommit Repository Name'
    Default: "cs-jenkins-demo"
Resources:
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${S3Bucket}.s3.amazonaws.com/iam.yaml'
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${S3Bucket}.s3.amazonaws.com/vpc.yaml'
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMStack
    Properties:
      TemplateURL: !Sub 'https://${S3Bucket}.s3.amazonaws.com/ec2.yaml'
      Parameters:
        InstanceProfile: !GetAtt IAMStack.Outputs.InstanceProfileName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnet1: !GetAtt VPCStack.Outputs.SubnetPublic1
        PublicSubnet2: !GetAtt VPCStack.Outputs.SubnetPublic2
        PrivateSubnet1: !GetAtt VPCStack.Outputs.SubnetPrivate1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.SubnetPrivate2
  CICDStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMStack
    Properties:
      TemplateURL: !Sub 'https://${S3Bucket}.s3.amazonaws.com/cicd.yaml'
      Parameters:
        RepositoryUrl: !Ref RepositoryUrl
        RepositoryName: !Ref RepositoryName
        PublicSubnet1: !GetAtt VPCStack.Outputs.SubnetPublic1