---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Resources to enable Falcon CI Lab'
Parameters:
  AWSManagedSecretsPolicy:
    Type: String
    Default: 'arn:aws:iam::aws:policy/SecretsManagerReadWrite'
  PermissionsBoundary:
    Type: String
    Default: 'BoundaryForAdministratorAccess'
Conditions:
  PermissionsBoundary: !Not [ !Equals [ !Ref PermissionsBoundary, '' ] ]
Resources:
  InstanceProfile: 
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: '/'
      Roles: 
        - 
          Ref: InstanceRole
  InstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      PermissionsBoundary:
        Fn::If:
          - PermissionsBoundary
          - !Sub 'arn:aws:iam::${AWS::AccountId}:policy/${PermissionsBoundary}'
          - Ref: AWS::NoValue
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - !Ref AWSManagedSecretsPolicy