---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Resources for Falcon CI Lab'
Resources:
  InstanceProfile: 
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: '/'
      Roles: 
        - 
          Ref: InstanceRole
  InstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::517716713836:policy/FalconContainerEcrPull
Outputs:
  InstanceProfileName:
    Value: !Ref InstanceProfile