on: [push]

jobs:
  cs-iac-action:
    runs-on: ubuntu-latest
    name: Scan Iac Files with CrowdStrike
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: ryanjpayne/action-test@v4
        with:
          target-directory: './'
          output-directory: './.crowdstrike/'
